version: "2.0"
services:
  rk_build:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: rk1808-build
    volumes:
      #- "./work:/root/work"
      - "../:/root/work"
    command: /bin/bash
    stdin_open: true # docker run -i
    tty: true # docker run -t
